import sys
import os
from uuid import uuid4
from datetime import datetime, timezone
from dotenv import load_dotenv

# ✅ Ensure project root is added to PYTHONPATH
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(ROOT_DIR)

load_dotenv()  # load .env variables

# ✅ Import after adjusting path
from core.embeddings import embed_text
from core.chroma_client import notes_collection

# ✅ Your sample notes (title, content)
notes = [
    ("dog", "The dog is a friendly domestic animal."),
    ("cat", "Cats often enjoy sleeping and are known for their independence."),
    ("america", "The president of the United States lives in the White House."),
    ("india", "India is known for its diverse culture and long history."),
    ("lion", "The lion is known as the king of the jungle."),
    ("tiger", "Tigers are solitary hunters and have striped fur."),
    ("elephant", "Elephants are the largest land animals on Earth."),
    ("giraffe", "Giraffes have long necks to reach leaves high in trees."),
    ("horse", "Horses have been used for travel for thousands of years."),
    ("cow", "Cows are farm animals that produce milk."),
    ("sheep", "Sheep are known for their wool coats."),
    ("goat", "Goats are agile animals often seen grazing on hills."),
    ("monkey", "Monkeys are social animals that live in groups."),
    ("zebra", "Zebras have black and white stripes used for camouflage."),
    ("bear", "Bears hibernate during winter to conserve energy."),
    ("wolf", "Wolves live and hunt in packs."),
    ("fox", "Foxes are known for their cunning behavior."),
    ("rabbit", "Rabbits have long ears and eat mostly plants."),
    ("kangaroo", "Kangaroos carry their young in a pouch."),
    ("panda", "Pandas eat mainly bamboo and are native to China."),
    ("whale", "Whales are the largest animals living in the oceans."),
    ("dolphin", "Dolphins are intelligent marine mammals."),
    ("shark", "Sharks are apex predators in the ocean."),
    ("octopus", "Octopuses have eight arms and can change color."),
    ("eagle", "Eagles have powerful eyesight and strong wings."),
    ("parrot", "Parrots can mimic human speech."),
    ("penguin", "Penguins are flightless birds that live in cold regions."),
    ("crow", "Crows are highly intelligent birds."),
    ("sparrow", "Sparrows are small birds commonly found in cities."),
    ("snake", "Snakes are cold-blooded reptiles that shed their skin."),
    ("lizard", "Lizards are adaptable reptiles found worldwide."),
    ("frog", "Frogs start their life as tadpoles in water."),
    ("fish", "Fish breathe through gills and live in water."),
    ("crab", "Crabs have hard shells and live near the sea."),
    ("butterfly", "Butterflies begin life as caterpillars."),
    ("ant", "Ants live and work in large colonies."),
    ("bee", "Bees produce honey and pollinate flowers."),
    ("spider", "Spiders spin webs to catch prey."),
    ("camel", "Camels can survive long periods without water."),
    ("desert", "Deserts are dry places with little rainfall."),
    ("rainforest", "Rainforests have dense vegetation and heavy rainfall."),
    ("mountain", "Mountains are elevated landforms rising above terrain."),
    ("river", "Rivers are natural flowing bodies of water."),
    ("ocean", "Oceans cover most of the Earth's surface."),
    ("lake", "Lakes are large bodies of freshwater."),
    ("island", "An island is land surrounded by water."),
    ("forest", "Forests are home to many plants and animals."),
    ("jungle", "Jungles are dense forests with thick vegetation."),
    ("valley", "A valley lies between mountains or hills."),
    ("city", "A city is a large urban settlement with many buildings."),
    ("village", "A village is a small rural community."),
    ("town", "A town is larger than a village but smaller than a city."),
    ("road", "Roads allow transportation and travel between places."),
    ("bridge", "Bridges help cross rivers or obstacles."),
    ("school", "Schools are places where students learn."),
    ("college", "Colleges provide higher education."),
    ("teacher", "Teachers help students learn new knowledge."),
    ("student", "Students study at schools and colleges."),
    ("doctor", "Doctors help treat illnesses."),
    ("nurse", "Nurses assist doctors and care for patients."),
    ("engineer", "Engineers design and build systems and structures."),
    ("farmer", "Farmers grow crops and raise animals."),
    ("chef", "Chefs prepare food in kitchens."),
    ("pilot", "Pilots fly airplanes."),
    ("driver", "Drivers operate vehicles for transportation."),
    ("artist", "Artists express creativity through art."),
    ("musician", "Musicians create and perform music."),
    ("writer", "Writers create stories, articles, or books."),
    ("scientist", "Scientists study the natural world through experiments."),
    ("astronaut", "Astronauts travel into space."),
    ("teacher", "A teacher educates students in various subjects."),
    ("lawyer", "Lawyers represent people in legal matters."),
    ("judge", "Judges oversee court proceedings."),
    ("police", "Police maintain law and order."),
    ("soldier", "Soldiers defend their country."),
    ("king", "A king rules a kingdom."),
    ("queen", "A queen shares leadership or rules a country."),
    ("president", "A president is the elected leader of a nation."),
    ("prime_minister", "Prime ministers lead the government's operations."),
    ("apple", "Apples are sweet fruits grown in orchards."),
    ("banana", "Bananas are long yellow fruits rich in potassium."),
    ("orange", "Oranges are citrus fruits high in vitamin C."),
    ("grape", "Grapes grow in clusters and can be used to make wine."),
    ("watermelon", "Watermelons are large fruits with red juicy flesh."),
    ("rice", "Rice is a staple food for many cultures."),
    ("bread", "Bread is made by baking dough."),
    ("milk", "Milk is a dairy product rich in calcium."),
    ("cheese", "Cheese is made by fermenting milk."),
    ("coffee", "Coffee is a brewed drink made from roasted beans."),
    ("tea", "Tea is made by steeping leaves in hot water."),
    ("computer", "Computers process information and perform calculations."),
    ("phone", "Phones allow communication between people."),
    ("internet", "The internet connects computers worldwide."),
    ("car", "Cars are vehicles used for transportation."),
    ("train", "Trains run on tracks and carry passengers."),
    ("airplane", "Airplanes fly through the sky to transport people."),
    ("ship", "Ships travel across water to transport goods."),
    ("bicycle", "Bicycles are vehicles powered by pedaling."),
    ("book", "Books contain written information or stories."),
    ("newspaper", "Newspapers report daily news."),
    ("television", "Television broadcasts visual media content."),
    ("pizza", "Pizza is a popular Italian dish with cheese and tomato sauce."),
    ("ice cream", "Ice cream is a frozen treat enjoyed worldwide."),
    ("mountain", "Mountains are large landforms that rise above the surrounding land."),
    ("river", "Rivers carry water from higher to lower ground and often flow to the sea."),
    ("ocean", "Oceans cover more than 70 percent of Earth's surface."),
    ("banana", "Bananas are a common fruit rich in potassium."),
    ("apple", "Apples come in many varieties and are often eaten raw."),
    ("car", "Cars are vehicles used for personal transportation."),
    ("train", "Trains run on tracks and can transport large numbers of passengers."),
    ("airplane", "Airplanes are used for fast travel between long distances."),
    ("computer", "Computers can perform calculations and run software applications."),
    ("keyboard", "A keyboard is an input device used to type text."),
    ("mouse", "A mouse is used to control a pointer on a computer screen."),
    ("television", "Televisions display visual content for entertainment and information."),
    ("camera", "Cameras capture images and videos."),
    ("book", "Books are written works that convey stories or information."),
    ("library", "A library stores books and other educational materials."),
    ("teacher", "A teacher educates students in various subjects."),
    ("student", "Students learn information and skills in educational settings."),
    ("school", "Schools are institutions designed for teaching and learning."),
    ("university", "Universities offer higher education and research opportunities."),
    ("city", "Cities are large human settlements with infrastructure and services."),
    ("village", "Villages are smaller settlements often found in rural areas."),
    ("forest", "Forests contain many trees and support various wildlife."),
    ("desert", "Deserts are dry regions with little rainfall."),
    ("rain", "Rain is precipitation that falls from clouds."),
    ("snow", "Snow forms when water freezes in the atmosphere and falls to the ground."),
    ("wind", "Wind is air in motion caused by differences in air pressure."),
    ("fire", "Fire is a chemical reaction that releases heat and light."),
    ("earthquake", "Earthquakes occur when tectonic plates shift."),
    ("volcano", "Volcanoes release lava and gases from beneath Earth's crust."),
    ("moon", "The moon is Earth's natural satellite that orbits around it."),
    ("sun", "The sun is the star at the center of our solar system."),
    ("planet", "Planets orbit stars and do not produce their own light."),
    ("star", "Stars are massive celestial bodies that emit light."),
    ("galaxy", "Galaxies are collections of stars, dust, and gas bound by gravity."),
    ("universe", "The universe contains all of space and time."),
    ("bicycle", "Bicycles are pedal-powered vehicles with two wheels."),
    ("motorcycle", "Motorcycles are two-wheeled motor-powered vehicles."),
    ("bus", "Buses can transport groups of passengers through cities or towns."),
    ("bridge", "Bridges allow passage over obstacles like rivers or valleys."),
    ("road", "Roads are built for vehicles to travel between locations."),
    ("building", "Buildings provide shelter and space for human use."),
    ("hospital", "Hospitals provide medical treatment and healthcare."),
    ("doctor", "Doctors diagnose and treat illnesses."),
    ("nurse", "Nurses assist doctors and provide patient care."),
    ("medicine", "Medicine helps treat and cure diseases."),
    ("pharmacy", "Pharmacies dispense medication prescribed by healthcare professionals."),
    ("engineer", "Engineers design and build structures, machines, and systems."),
    ("scientist", "Scientists study the natural world through experiments and research."),
    ("lawyer", "Lawyers advise and represent clients in legal matters."),
    ("judge", "Judges oversee court proceedings and make legal rulings."),
    ("police", "Police enforce laws and maintain public safety."),
    ("firefighter", "Firefighters extinguish fires and respond to emergencies."),
    ("soldier", "Soldiers serve in the armed forces to protect a country."),
    ("artist", "Artists create visual, musical, or performance works."),
    ("musician", "Musicians create and perform music."),
    ("painter", "Painters create artwork using paint on surfaces."),
    ("writer", "Writers produce written works like books, articles, or scripts."),
    ("poet", "Poets write poems that express feelings and ideas using language creatively."),
    ("singer", "Singers perform songs using their voices."),
    ("actor", "Actors portray characters in plays, films, or shows."),
    ("director", "Directors oversee the creative vision of films or performances."),
    ("farmer", "Farmers grow crops and raise livestock for food."),
    ("chef", "Chefs prepare food professionally in restaurants."),
    ("baker", "Bakers make bread, pastries, and other baked goods."),
    ("engine", "Engines convert energy into mechanical motion."),
    ("battery", "Batteries store and release electrical energy."),
    ("phone", "Phones allow communication over long distances."),
    ("smartphone", "Smartphones combine phone functions with computing capabilities."),
    ("internet", "The internet connects computers globally for communication and data exchange."),
    ("website", "Websites are online pages accessible via the internet."),
    ("email", "Email is electronic mail used for digital communication."),
    ("software", "Software consists of programs that run on computers."),
    ("hardware", "Hardware refers to the physical components of a computer."),
    ("robot", "Robots are machines capable of performing automated tasks."),
    ("drone", "Drones are unmanned aerial vehicles controlled remotely."),
    ("satellite", "Satellites orbit Earth and support communication and navigation."),
    ("map", "Maps represent geographic locations and features."),
    ("weather", "Weather describes atmospheric conditions at a given time."),
    ("climate", "Climate refers to long-term weather patterns."),
    ("temperature", "Temperature measures how hot or cold something is."),
    ("energy", "Energy is the ability to do work or cause change."),
    ("electricity", "Electricity is the flow of electric charge used to power devices."),
    ("gravity", "Gravity is the force that pulls objects toward each other."),
    ("time", "Time measures the duration of events."),
    ("history", "History records past events and civilizations."),
    ("economy", "The economy describes how money and resources are exchanged."),
    ("government", "Governments create laws and manage public resources."),
    ("democracy", "Democracy is a system where citizens vote to make decisions."),
    ("language", "Languages are systems of communication using symbols or sounds."),
    ("culture", "Culture includes traditions, beliefs, and customs of a society."),
    ("music", "Music is organized sound that expresses emotion or ideas."),
    ("dance", "Dance uses body movement to express feelings or tell stories."),
    ("sport", "Sports involve physical activity and competition."),
    ("football", "Football is a popular team sport played worldwide."),
    ("cricket", "Cricket is a bat-and-ball game played between two teams."),
    ("basketball", "Basketball involves shooting a ball into a hoop."),
    ("tennis", "Tennis is played by hitting a ball over a net using rackets."),
    ("swimming", "Swimming involves moving through water using body motions."),
    ("running", "Running is a form of physical exercise that involves moving quickly on foot."),
    ("cycling", "Cycling is the activity of riding bicycles for transport or sport."),
    ("hiking", "Hiking is walking in natural environments, often on trails or mountains."),
    ("skiing", "Skiing involves gliding over snow using skis attached to boots."),
    ("snowboarding", "Snowboarding is sliding down snow-covered slopes on a board."),
    ("yoga", "Yoga is a physical, mental, and spiritual practice involving postures and breathing."),
    ("meditation", "Meditation is the practice of focused attention and mindfulness."),
    ("photography", "Photography is the art of capturing images using cameras."),
    ("painting", "Painting is creating artwork with paints on a canvas or surface."),
    ("sculpture", "Sculpture is creating three-dimensional art by carving or molding materials."),
    ("architecture", "Architecture is the art and science of designing buildings and structures."),
    ("design", "Design involves planning and creating products, visuals, or systems."),
    ("fashion", "Fashion refers to clothing styles and trends popular in a period."),
    ("clothing", "Clothing covers the body and provides warmth, protection, or style."),
    ("shoes", "Shoes are worn on feet for protection and comfort."),
    ("hat", "Hats are worn on the head for style or protection from the elements."),
    ("bag", "Bags are used to carry personal belongings."),
    ("jewelry", "Jewelry includes ornaments like rings, necklaces, and bracelets."),
    ("watch", "Watches are used to keep track of time."),
    ("glasses", "Glasses help improve vision or protect the eyes."),
    ("camera", "Cameras capture photos and videos of moments or scenes."),
    ("microphone", "Microphones capture sound for recording or amplification."),
    ("speaker", "Speakers output audio for listening."),
    ("headphones", "Headphones are worn over or in the ears to listen to audio privately."),
    ("guitar", "The guitar is a stringed instrument played by strumming or plucking."),
    ("piano", "The piano is a keyboard instrument used for music."),
    ("violin", "The violin is a small string instrument played with a bow."),
    ("drums", "Drums are percussion instruments used to create rhythm."),
    ("flute", "The flute is a woodwind instrument producing sound from air flow."),
    ("trumpet", "The trumpet is a brass instrument played by blowing air through lips."),
    ("saxophone", "The saxophone is a woodwind instrument used in jazz and classical music."),
    ("orchestra", "An orchestra is a group of musicians playing various instruments together."),
    ("band", "A band is a group of musicians playing popular or rock music."),
    ("concert", "A concert is a live performance of music for an audience."),
    ("festival", "Festivals are events celebrating music, culture, or traditions."),
    ("theater", "Theater is a place for live performances of plays and drama."),
    ("movie", "Movies are films created to entertain, inform, or tell stories."),
    ("film", "Film is a medium for recording visual stories."),
    ("actor", "Actors perform roles in movies, TV, or theater productions."),
    ("director", "Directors guide the creative vision of a performance or film."),
    ("producer", "Producers oversee the production process and financing of media."),
    ("script", "A script is the written text for a play, movie, or show."),
    ("novel", "Novels are long fictional stories written in prose."),
    ("short story", "Short stories are brief fictional narratives."),
    ("poem", "Poems use creative language and structure to convey meaning."),
    ("article", "Articles are written pieces of information for publications."),
    ("journal", "Journals record events, research, or personal experiences."),
    ("magazine", "Magazines are periodicals covering specific topics or interests."),
    ("newspaper", "Newspapers report news and current events."),
    ("internet", "The internet is a global network connecting computers for communication."),
    ("website", "Websites provide information or services online."),
    ("blog", "Blogs are online journals or articles updated regularly."),
    ("forum", "Forums are online spaces for discussion and questions."),
    ("chat", "Chats allow real-time online conversation."),
    ("email", "Email is electronic communication sent digitally."),
    ("message", "Messages are written or electronic communications."),
    ("call", "Calls are voice communications between people."),
    ("video call", "Video calls allow visual and audio communication remotely."),
    ("social media", "Social media platforms connect people and share content."),
    ("Facebook", "Facebook is a social media platform for connecting and sharing."),
    ("Twitter", "Twitter is a platform for microblogging and short updates."),
    ("Instagram", "Instagram is a social platform for sharing photos and videos."),
    ("TikTok", "TikTok is a platform for short-form video content."),
    ("YouTube", "YouTube is a platform for watching and sharing videos."),
    ("Netflix", "Netflix is a streaming platform for movies and TV shows."),
    ("Amazon", "Amazon is an e-commerce platform for buying products online."),
    ("shopping", "Shopping involves purchasing goods or services."),
    ("store", "Stores sell products to customers."),
    ("market", "Markets are places where goods are bought and sold."),
    ("supermarket", "Supermarkets sell groceries and household items."),
    ("restaurant", "Restaurants serve food and drinks to customers."),
    ("cafe", "Cafes serve coffee and light meals."),
    ("bar", "Bars serve drinks and provide social spaces."),
    ("pub", "Pubs are establishments serving drinks and casual meals."),
    ("hotel", "Hotels provide lodging for travelers."),
    ("resort", "Resorts are vacation destinations with amenities."),
    ("beach", "Beaches are sandy areas near bodies of water."),
    ("lake", "Lakes are inland bodies of water surrounded by land."),
    ("river", "Rivers are flowing bodies of water."),
    ("waterfall", "Waterfalls occur when water drops over a vertical edge."),
    ("forest", "Forests are areas densely populated with trees."),
    ("jungle", "Jungles are dense tropical forests with diverse wildlife."),
    ("desert", "Deserts are dry areas with little rainfall."),
    ("mountain", "Mountains are large natural elevations of the earth's surface."),
    ("valley", "Valleys are low areas between hills or mountains."),
    ("island", "Islands are land surrounded by water."),
    ("peninsula", "Peninsulas are land areas surrounded by water on three sides."),
    ("continent", "Continents are large landmasses on Earth."),
    ("earth", "Earth is the third planet from the sun."),
    ("moon", "The moon orbits around Earth."),
    ("sun", "The sun is the star at the center of our solar system."),
    ("mars", "Mars is the fourth planet from the sun."),
    ("jupiter", "Jupiter is the largest planet in our solar system."),
    ("saturn", "Saturn is known for its rings made of ice and rock."),
    ("venus", "Venus is the second planet from the sun."),
    ("mercury", "Mercury is the closest planet to the sun."),
    ("neptune", "Neptune is the farthest planet from the sun."),
    ("uranus", "Uranus is an ice giant in our solar system."),
    ("pluto", "Pluto is a dwarf planet in the solar system."),
    ("ocean", "Oceans are vast bodies of salt water covering most of the Earth."),
    ("sea", "Seas are smaller than oceans and partially enclosed by land."),
    ("wave", "Waves are the movement of water on the surface of seas or oceans."),
    ("tide", "Tides are the rising and falling of sea levels caused by the moon and sun."),
    ("storm", "Storms are violent weather conditions with strong winds and rain."),
    ("hurricane", "Hurricanes are intense tropical storms with high winds and heavy rain."),
    ("tornado", "Tornadoes are rapidly rotating columns of air in contact with the ground."),
    ("rain", "Rain is water droplets falling from clouds."),
    ("snow", "Snow is frozen precipitation in the form of ice crystals."),
    ("hail", "Hail consists of balls or lumps of ice falling during storms."),
    ("sleet", "Sleet is a mix of rain and snow or partially melted ice."),
    ("fog", "Fog is a thick cloud of tiny water droplets near the ground."),
    ("cloud", "Clouds are visible masses of water vapor in the sky."),
    ("sunshine", "Sunshine is the light and warmth from the sun."),
    ("rainbow", "Rainbows are arcs of colors appearing in the sky after rain."),
    ("thunder", "Thunder is the sound caused by lightning."),
    ("lightning", "Lightning is a sudden electrical discharge in the atmosphere."),
    ("wind", "Wind is air in motion."),
    ("breeze", "A breeze is a gentle wind."),
    ("gust", "A gust is a sudden strong burst of wind."),
    ("earthquake", "Earthquakes are shaking of the ground caused by tectonic movement."),
    ("volcano", "Volcanoes are openings in the Earth's crust that release lava."),
    ("lava", "Lava is molten rock that erupts from a volcano."),
    ("geyser", "Geysers are hot springs that periodically spout water and steam."),
    ("cave", "Caves are natural underground spaces."),
    ("cliff", "Cliffs are steep rock faces."),
    ("valley", "Valleys are low areas between hills or mountains."),
    ("plain", "Plains are large areas of flat or gently rolling land."),
    ("plateau", "Plateaus are elevated flatlands."),
    ("forest", "Forests are large areas filled with trees."),
    ("rainforest", "Rainforests are dense tropical forests with high rainfall."),
    ("savanna", "Savannas are grassy plains with few trees."),
    ("tundra", "Tundras are cold, treeless regions."),
    ("desert", "Deserts are arid regions with little rainfall."),
    ("canyon", "Canyons are deep valleys with steep sides."),
    ("waterfall", "Waterfalls occur when water flows over a vertical drop."),
    ("river", "Rivers are flowing bodies of water."),
    ("lake", "Lakes are large bodies of water surrounded by land."),
    ("pond", "Ponds are small bodies of water."),
    ("island", "Islands are land surrounded by water."),
    ("archipelago", "Archipelagos are groups of islands."),
    ("mountain", "Mountains are large natural elevations of the earth's surface."),
    ("hill", "Hills are smaller elevations than mountains."),
    ("volcano", "Volcanoes are openings that release lava and gases."),
    ("glacier", "Glaciers are large masses of ice slowly moving over land."),
    ("iceberg", "Icebergs are large floating pieces of ice."),
    ("cave", "Caves are natural underground spaces."),
    ("desert", "Deserts are regions with very little rainfall."),
    ("forest", "Forests are dense collections of trees and plants."),
    ("jungle", "Jungles are dense tropical forests."),
    ("prairie", "Prairies are large open grasslands."),
    ("meadow", "Meadows are fields of grass and flowers."),
    ("valley", "Valleys are low areas between hills or mountains."),
    ("cliff", "Cliffs are steep rock faces."),
    ("plateau", "Plateaus are elevated flatlands."),
    ("bay", "Bays are bodies of water partially enclosed by land."),
    ("gulf", "Gulfs are large coastal inlets."),
    ("harbor", "Harbors are places where ships dock safely."),
    ("port", "Ports are facilities for loading and unloading ships."),
    ("bridge", "Bridges connect two points over water or obstacles."),
    ("tunnel", "Tunnels are underground passages."),
    ("road", "Roads are paved paths for vehicles."),
    ("street", "Streets are public roads in towns or cities."),
    ("highway", "Highways are major roads connecting cities."),
    ("railway", "Railways are tracks for trains."),
    ("train", "Trains are vehicles that run on tracks."),
    ("subway", "Subways are underground trains in cities."),
    ("bus", "Buses are vehicles carrying passengers on roads."),
    ("car", "Cars are vehicles for personal transportation."),
    ("bicycle", "Bicycles are two-wheeled vehicles powered by pedaling."),
    ("motorcycle", "Motorcycles are two-wheeled motor vehicles."),
    ("airplane", "Airplanes are aircraft that fly through the air."),
    ("helicopter", "Helicopters are aircraft that hover and fly vertically."),
    ("ship", "Ships are large vessels for traveling on water."),
    ("boat", "Boats are smaller vessels used on rivers or seas."),
    ("ferry", "Ferries transport people or vehicles across water."),
    ("spacecraft", "Spacecraft travel in outer space."),
    ("satellite", "Satellites orbit planets or other celestial bodies."),
    ("astronaut", "Astronauts travel and work in space."),
    ("rocket", "Rockets launch spacecraft into space."),
    ("telescope", "Telescopes allow observation of distant objects in space."),
    ("planet", "Planets are celestial bodies orbiting a star."),
    ("star", "Stars are luminous spheres of plasma in space."),
    ("galaxy", "Galaxies are vast systems of stars, gas, and dust."),
    ("universe", "The universe contains all of space and time."),
    ("atom", "Atoms are the basic units of matter."),
    ("molecule", "Molecules are groups of atoms bonded together."),
    ("cell", "Cells are the basic units of life."),
    ("tissue", "Tissues are groups of cells performing a function."),
    ("organ", "Organs are structures with specific biological functions."),
    ("system", "Systems are groups of organs working together."),
    ("organism", "Organisms are individual living beings."),
    ("species", "Species are groups of similar organisms."),
    ("population", "Populations are groups of organisms of the same species."),
    ("community", "Communities are interacting populations."),
    ("ecosystem", "Ecosystems include living and non-living components."),
    ("biome", "Biomes are large ecological areas with distinct climates."),
    ("biodiversity", "Biodiversity refers to the variety of life forms in an ecosystem."),
    ("environment", "The environment is the surrounding conditions and influences."),
    ("climate", "Climate is the long-term pattern of weather in a region."),
    ("weather", "Weather is the short-term state of the atmosphere."),
    ("temperature", "Temperature measures how hot or cold something is."),
    ("humidity", "Humidity is the amount of water vapor in the air."),
    ("pressure", "Pressure is the force exerted by air or fluids."),
    ("wind", "Wind is the movement of air."),
    ("storm", "Storms are violent atmospheric disturbances."),
    ("rain", "Rain is precipitation in the form of water droplets."),
    ("snow", "Snow is frozen precipitation."),
    ("hail", "Hail consists of balls of ice falling from the sky."),
    ("fog", "Fog is a thick cloud near the ground."),
    ("cloud", "Clouds are visible masses of water vapor."),
    ("sun", "The sun is the star at the center of the solar system."),
    ("moon", "The moon orbits Earth."),
    ("earth", "Earth is the third planet from the sun."),
    ("mars", "Mars is the fourth planet from the sun."),
    ("jupiter", "Jupiter is the largest planet."),
    ("saturn", "Saturn is famous for its rings."),
    ("venus", "Venus is the second planet."),
    ("mercury", "Mercury is closest to the sun."),
    ("neptune", "Neptune is the eighth planet."),
    ("uranus", "Uranus is an ice giant."),
    ("pluto", "Pluto is a dwarf planet."),
]


BATCH_SIZE = 50
def bulk_import():
    total = len(notes)
    print(f"🚀 Starting bulk import of {total} notes in batches of {BATCH_SIZE}...")

    for i in range(0, total, BATCH_SIZE):
        batch = notes[i : i + BATCH_SIZE]

        ids = []
        documents = []
        embeddings = []
        metadatas = []

        for title, content in batch:
            vector = embed_text(content)
            note_id = str(uuid4())
            now = datetime.now(timezone.utc).isoformat()

            ids.append(note_id)
            documents.append(content)
            embeddings.append(vector)
            metadatas.append({
                "title": title,
                "created_at": now,
                "updated_at": now
            })

        # ✅ Insert batch
        notes_collection.add(
            ids=ids,
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas
        )

        print(f"✅ Imported {len(batch)} notes (batch {i//BATCH_SIZE + 1})")

    print("🎉 Bulk import completed successfully!")


if __name__ == "__main__":
    bulk_import()